version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3.7
    steps:
      - run: sudo apt install -y gmsh git-lfs
      - run: python3 -m pip install -U pytest pytest-cov --user
      - checkout
      - run: git lfs pull
      #
      - run: python3 -m pip install .[all] --user
      # The tests
      - run: 
          command: pytest --maxfail=1 --cov optimesh
          working_directory: test/
          environment:
            MPLBACKEND: Agg
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
