version: 2

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      - run: apt install -y git python3-pip gmsh
      - run: pip3 install -U pytest pytest-cov black flake8
      - checkout
      - run: pip3 install .[all]
      - run: pip3 install -r test_requirements.txt
      # format and lint
      - run: LC_ALL=C.UTF-8 black --check setup.py optimesh/ test/*.py
      - run: flake8 setup.py optimesh/ test/*.py
      # The tests
      - run: cd test/ && pytest --maxfail=1 --cov optimesh
      # submit to codecov
      - run: apt install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
