version: 2

jobs:
  lint:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update
      - run: apt install -y python3-pip
      - run: pip3 install -U black flake8
      - run: LC_ALL=C.UTF-8 black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      - run: apt install -y git python3-pip gmsh git-lfs
      - run: pip3 install -U pytest pytest-cov
      - checkout
      - run: git lfs pull
      #
      - run: pip3 install .[all]
      # The tests
      - run: cd test/ && MPLBACKEND=Agg pytest --maxfail=1 --cov optimesh
      # submit to codecov
      - run: apt install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
